name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Load from versions.txt later on
# Or do this in the docker file
env:
  MICROMAMBA_VERSION: "1.5.8"
  ENVIRONMENT_FILE: "env.yaml"
  PANDOC_VERSION: "3.2"
  PANDOC_CLI_VERSION: "3.2"
  PANDOC_CROSSREF_VERSION: "0.3.17.1"
  LUA_VERSION: "5.4"
  PANDOC_PLOT_VERSION: "1.8.0"
  IMAGE_NAME: "aih-pandoc"
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}  
  TEST_TAG: ${{ secrets.DOCKER_HUB_USERNAME }}/aih-pandoc:test
  LATEST_TAG: ${{ secrets.DOCKER_HUB_USERNAME }}/aih-pandoc:final  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:test
          # platforms: linux/amd64
          #, linux/arm64
          # platforms: linux/arm64, 
          build-args: |
            MICROMAMBA_VERSION=${{ env.MICROMAMBA_VERSION }}
            ENVIRONMENT_FILE=${{ env.ENVIRONMENT_FILE }}
            PANDOC_VERSION=${{ env.PANDOC_VERSION }}
            PANDOC_CLI_VERSION=${{ env.PANDOC_CLI_VERSION }}
            PANDOC_CROSSREF_VERSION=${{ env.PANDOC_CROSSREF_VERSION }}
            LUA_VERSION=${{ env.LUA_VERSION }}
            PANDOC_PLOT_VERSION=${{ env.PANDOC_PLOT_VERSION }}
      - name: Test
        run: |
          docker run --rm ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:test /bin/bash ./run_tests.sh
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          # , linux/arm64
          # platforms: linux/arm64, linux/amd64
          build-args: |
            MICROMAMBA_VERSION=${{ env.MICROMAMBA_VERSION }}
            ENVIRONMENT_FILE=${{ env.ENVIRONMENT_FILE }}
            PANDOC_VERSION=${{ env.PANDOC_VERSION }}
            PANDOC_CLI_VERSION=${{ env.PANDOC_CLI_VERSION }}
            PANDOC_CROSSREF_VERSION=${{ env.PANDOC_CROSSREF_VERSION }}
            LUA_VERSION=${{ env.LUA_VERSION }}
            PANDOC_PLOT_VERSION=${{ env.PANDOC_PLOT_VERSION }}          
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:final


