name: Build Docker Image

on:
  push:
    branches:
      - main
      - 'refs/tags/v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g., v1.2.3 or latest)'
        required: true
        default: ''

env:
  IMAGE_NAME: "aih-pandoc"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag == '' ? 'main' : github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set build environment variables
        id: set-env
        run: |
          VERSION_FILE="versions.txt"
          if [ -f "$VERSION_FILE" ]; then
            echo "Found settings file $VERSION_FILE"
            cat $VERSION_FILE
            source $VERSION_FILE
            echo "MICROMAMBA_VERSION=${MICROMAMBA_VERSION}" >> $GITHUB_ENV
            echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
            echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
            echo "ENVIRONMENT_FILE=${ENVIRONMENT_FILE}" >> $GITHUB_ENV
            echo "PANDOC_VERSION=${PANDOC_VERSION}" >> $GITHUB_ENV
            echo "PANDOC_CLI_VERSION=${PANDOC_CLI_VERSION}" >> $GITHUB_ENV
            echo "PANDOC_CROSSREF_VERSION=${PANDOC_CROSSREF_VERSION}" >> $GITHUB_ENV
            echo "LUA_VERSION=${LUA_VERSION}" >> $GITHUB_ENV
            echo "PANDOC_PLOT_VERSION=${PANDOC_PLOT_VERSION}" >> $GITHUB_ENV
          else
            echo "Settings file $VERSION_FILE not found"
            exit 1
          fi
          if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ "${{ github.event.inputs.tag }}" == "" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          platforms: linux/amd64
          build-args: |
            MICROMAMBA_VERSION=${{ env.MICROMAMBA_VERSION }}
            ENVIRONMENT_FILE=${{ env.ENVIRONMENT_FILE }}
            PANDOC_VERSION=${{ env.PANDOC_VERSION }}
            PANDOC_CLI_VERSION=${{ env.PANDOC_CLI_VERSION }}
            PANDOC_CROSSREF_VERSION=${{ env.PANDOC_CROSSREF_VERSION }}
            LUA_VERSION=${{ env.LUA_VERSION }}
            PANDOC_PLOT_VERSION=${{ env.PANDOC_PLOT_VERSION }}

      - name: Test
        run: |
          docker run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} /bin/bash ./run_tests.sh

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          build-args: |
            MICROMAMBA_VERSION=${{ env.MICROMAMBA_VERSION }}
            ENVIRONMENT_FILE=${{ env.ENVIRONMENT_FILE }}
            PANDOC_VERSION=${{ env.PANDOC_VERSION }}
            PANDOC_CLI_VERSION=${{ env.PANDOC_CLI_VERSION }}
            PANDOC_CROSSREF_VERSION=${{ env.PANDOC_CROSSREF_VERSION }}
            LUA_VERSION=${{ env.LUA_VERSION }}
            PANDOC_PLOT_VERSION=${{ env.PANDOC_PLOT_VERSION }}          
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
